// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Return value of `apply_changeset`.
 */
export type ApplyReport = { applied_count: number, skipped_count: number, };
