// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListDensitySetting } from "./ListDensitySetting";
import type { ThemeSetting } from "./ThemeSetting";

/**
 * User-facing subset of [`lantern_io::Settings`].
 *
 * Runtime-managed fields (recent files, recoverable documents, session flag)
 * are intentionally omitted: the UI edits preferences, not internal state.
 */
export type AppSettings = { theme: ThemeSetting, dead_link_checker_opt_in: boolean, recent_files_max: number, crash_recovery_enabled: boolean, 
/**
 * List-row density for the bookmark list pane.
 */
list_density: ListDensitySetting, 
/**
 * Path to the on-disk settings file (read-only; shown for the "locate
 * settings" affordance in the UI).
 */
settings_path: string, 
/**
 * Path to the directory holding `*.lantern-rules.toml` files.
 */
rules_dir: string, };
