// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListDensitySetting } from "./ListDensitySetting";
import type { ThemeSetting } from "./ThemeSetting";

/**
 * The user-editable part of [`lantern_io::Settings`] plus where it lives.
 */
export type AppSettings = { theme: ThemeSetting, dead_link_checker_opt_in: boolean, recent_files_max: number, crash_recovery_enabled: boolean, 
/**
 * List-row density for the bookmark list pane.
 */
list_density: ListDensitySetting, 
/**
 * Read-only: ignored by `update_settings`.
 */
settings_path: string, 
/**
 * Read-only: ignored by `update_settings`.
 */
rules_dir: string, };
