// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build-time facts surfaced in the About pane.
 */
export type BuildInfo = { 
/**
 * Crate version from `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * `"default"` (full build) or `"offline-only"` (no `checker` feature).
 */
build_flavor: string, 
/**
 * `rustc -V` output captured by `build.rs`.
 */
rust_version: string, 
/**
 * Always `None`: no git stamp is embedded yet.
 */
git_commit: string | null, 
/**
 * SPDX license expression.
 */
license: string, 
/**
 * Whether the Windows signing job signed this binary (`LANTERN_SIGNED`
 * at build time).  Always `false` for local builds.
 */
signed: boolean, };
