// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build-time facts surfaced in the About pane.
 */
export type BuildInfo = { 
/**
 * Crate version from `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * `"default"` (full build) or `"offline-only"` (no `checker` feature).
 */
build_flavor: string, 
/**
 * Compile-time Rust version, captured by `build.rs`.
 */
rust_version: string, 
/**
 * Reserved for future use; always `None` until a git stamp is wired in.
 */
git_commit: string | null, 
/**
 * SPDX-style license string (matches the workspace `LICENSE` file).
 */
license: string, 
/**
 * Informational reference path to the ADR index.
 */
adr_index_path: string, 
/**
 * `true` if the binary was Authenticode-signed at build time.  Driven
 * by the `LANTERN_SIGNED=1` environment variable read by the build
 * script, which the CI sign-windows job sets after `signtool` succeeds.
 * Local dev builds always report `false`.
 */
signed: boolean, };
