// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSpan } from "./DiffSpan";

/**
 * One proposed change, as shown on the review surface.
 */
export type ChangeEntry = { 
/**
 * Index into the change set; passed back in `approvals` for
 * `apply_changeset`.
 */
index: number, node_id: number, 
/**
 * `"url"`, `"title"`, `"folder_name"`, `"node"` (deletion) or
 * `"flag:<name>"`.
 */
field: string, before: string, after: string, 
/**
 * Character diff spans that rebuild `before`.
 */
before_spans: Array<DiffSpan>, 
/**
 * Character diff spans that rebuild `after`.
 */
after_spans: Array<DiffSpan>, treatment_id: string, rationale: string, destructive: boolean, 
/**
 * Initial approval state (true for non-destructive changes).
 */
approved: boolean, 
/**
 * Title (bookmark) or name (folder) before the change; for a deletion
 * the only description of the node.
 */
node_title: string, 
/**
 * The node's URL before the change (bookmarks only).
 */
node_url: string | null, 
/**
 * Folder names from the top of the document down to the node's parent
 * (the root folder itself is left out).
 */
location: Array<string>, };
