// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSpan } from "./DiffSpan";

/**
 * Serialisable representation of one proposed change, sent to the preview
 * panel.
 */
export type ChangeEntry = { 
/**
 * Index into the change set; passed back in `approvals` for
 * `apply_changeset`.
 */
index: number, node_id: number, 
/**
 * "url" | "title" | "folder_name"
 */
field: string, before: string, after: string, 
/**
 * Char-level diff spans reconstructing `before` (use for strikethrough rendering).
 */
before_spans: Array<DiffSpan>, 
/**
 * Char-level diff spans reconstructing `after` (use for highlight rendering).
 */
after_spans: Array<DiffSpan>, treatment_id: string, rationale: string, destructive: boolean, 
/**
 * Initial approval state (true for non-destructive changes).
 */
approved: boolean, };
