// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeEntry } from "./ChangeEntry";

/**
 * Return value of `run_pass`: what the UI shows in the preview panel.
 */
export type ChangeSetPreview = { changeset_id: number, rule_set_name: string, changes: Array<ChangeEntry>, };
