// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirror of [`lantern_core::model::merge::ConflictStrategy`]; the core
 * stays serde-free.
 */
export type ConflictStrategyView = "keep_first" | "keep_newest" | "keep_both";
