// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * IPC mirror of [`lantern_core::model::merge::ConflictStrategy`].
 *
 * The two enums are kept separate so the core stays serde-free and the IPC
 * boundary controls its own JSON shape.  Use the `From` impls below to
 * convert.
 */
export type ConflictStrategyView = "keep_first" | "keep_newest" | "keep_both";
