// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffTag } from "./DiffTag";

/**
 * One run of characters in a change-preview diff.
 */
export type DiffSpan = { tag: DiffTag, text: string, };
