// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of one span in a diff result.
 */
export type DiffTag = "equal" | "removed" | "added";
