// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffTag } from "./DiffTag";

/**
 * One contiguous run of characters in a change-preview diff (mirror of
 * [`lantern_core::sanitize::diff::DiffSpan`]).
 */
export type DiffSpan = { tag: DiffTag, text: string, };
