// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookmarkSnapshotView } from "./BookmarkSnapshotView";
import type { ModifiedBookmarkView } from "./ModifiedBookmarkView";

/**
 * Three-way diff between two open tabs, the result of `compare_tabs`.
 */
export type DocDiffReport = { left_title: string, right_title: string, added: Array<BookmarkSnapshotView>, removed: Array<BookmarkSnapshotView>, modified: Array<ModifiedBookmarkView>, };
