// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";

export type FolderItem = { id: number, kind: ItemKind, title: string, url: string | null, 
/**
 * URL host without a leading `www.`, if the URL parses.
 */
domain: string | null, add_date: number | null, last_modified: number | null, };
