// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderItem } from "./FolderItem";

export type ItemPage = { items: Array<FolderItem>, 
/**
 * Total items in the folder before pagination.
 */
total: number, };
