// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkCheckEntry } from "./LinkCheckEntry";

export type LinkCheckReport = { entries: Array<LinkCheckEntry>, total_bookmarks: number, 
/**
 * Entries that went to the network (not skipped).
 */
probed: number, };
