// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkStatusView } from "./LinkStatusView";

/**
 * One probed bookmark.
 */
export type LinkCheckEntry = { node_id: number, url: string, title: string, status: LinkStatusView, 
/**
 * Milliseconds until a status was known; `0` for skipped URLs.
 */
elapsed_ms: number, };
