// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkStatusView } from "./LinkStatusView";

/**
 * One row of [`LinkCheckReport::entries`]: the bookmark and what came back
 * from probing it.
 *
 * The `status` field mirrors [`lantern_net::LinkStatus`] using the same
 * internally-tagged JSON shape so the UI can pattern-match by `status.kind`.
 */
export type LinkCheckEntry = { node_id: number, url: string, title: string, status: LinkStatusView, 
/**
 * Time-to-status, milliseconds.  `0` for skipped URLs.
 */
elapsed_ms: number, };
