// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkCheckEntry } from "./LinkCheckEntry";

export type LinkCheckReport = { entries: Array<LinkCheckEntry>, 
/**
 * Number of bookmarks the document contained when the report was built.
 */
total_bookmarks: number, 
/**
 * Number of entries that actually hit the network (`total - skipped`).
 */
probed: number, };
