// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReasonView } from "./SkipReasonView";

/**
 * Mirror of [`lantern_net::LinkStatus`], tagged by `kind`.  A local type
 * because `ts-rs` cannot derive bindings for another crate's types.
 */
export type LinkStatusView = { "kind": "ok", code: number, } | { "kind": "redirect", code: number, } | { "kind": "client_error", code: number, } | { "kind": "server_error", code: number, } | { "kind": "timeout" } | { "kind": "network_error", detail: string, } | { "kind": "skipped", reason: SkipReasonView, };
