// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * One parsed log entry: output of `get_logs`.
 */
export type LogEntry = { 
/**
 * ISO 8601 timestamp string copied verbatim from the log file.
 */
timestamp: string, level: LogLevel, message: string, };
