// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity level.  `Info` is the default for unrecognised level strings so
 * malformed lines don't surface as errors to the user.
 */
export type LogLevel = "info" | "warn" | "error";
