// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subtree to copy into a merge.
 */
export type MergePickRequest = { source_tab_id: number, root_node_id: number, };
