// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookmarkSnapshotView } from "./BookmarkSnapshotView";

export type ModifiedBookmarkView = { before: BookmarkSnapshotView, after: BookmarkSnapshotView, };
