// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecoveryRestoreReport = { restored_tab_ids: Array<number>, restored_paths: Array<string>, failed_paths: Array<string>, };
