// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary for a single rule set, used by `list_rule_sets`.
 */
export type RuleSetSummary = { name: string, 
/**
 * Treatment count (for the card subtitle in the UI).
 */
treatment_count: number, 
/**
 * True for the three built-in rule sets that ship with Lantern.
 */
is_builtin: boolean, 
/**
 * Absolute path to the `.lantern-rules.toml` file.
 */
path: string, };
