// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of `list_rule_sets`.
 */
export type RuleSetSummary = { name: string, treatment_count: number, is_builtin: boolean, 
/**
 * Path of the `.lantern-rules.toml` file.
 */
path: string, };
