// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One treatment in a rule set.
 */
export type RuleSetTreatment = { id: string, 
/**
 * Configuration as JSON (e.g. `{"params": ["fbclid"]}`); `null` for
 * treatments without parameters.
 */
config: Record<string, unknown> | null, };
