// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ordered entry in a rule-set, exposed to the UI.
 */
export type RuleSetTreatment = { id: string, 
/**
 * JSON-shaped current config (e.g. `{"params": ["fbclid"]}`).  `null`
 * when the treatment has no parameters or when it is unconfigured.
 */
config: Record<string, unknown> | null, };
