// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleSetTreatment } from "./RuleSetTreatment";

/**
 * One rule set with its ordered treatments, for the editor.
 */
export type RuleSetDetail = { name: string, 
/**
 * Ordered treatment ids.
 */
treatment_ids: Array<string>, 
/**
 * The same treatments, each with its configuration.
 */
treatments: Array<RuleSetTreatment>, is_builtin: boolean, path: string, };
