// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderItem } from "./FolderItem";

export type SearchResults = { items: Array<FolderItem>, total: number, };
