// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the keyboard-shortcuts table.
 */
export type ShortcutBinding = { 
/**
 * Stable identifier (e.g. `"open_file"`), used as the React `key`.
 */
action_id: string, 
/**
 * Human-readable label (e.g. `"Open file"`).
 */
label: string, 
/**
 * Pretty-printed key combo (e.g. `"Ctrl+Shift+D"`).
 */
key_combo: string, 
/**
 * Grouping bucket: `"File"`, `"Edit"`, `"View"`, `"Tools"`, `"App"`.
 */
category: string, };
