// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the keyboard-shortcuts table.  Hardcoded for v0.0.7; rebinding
 * is deferred to a later milestone (PRD §8.9 captures the canonical list).
 */
export type ShortcutBinding = { 
/**
 * Stable identifier (e.g. `"open_file"`).  Used as the React `key` and as
 * the future hook for user-rebinding.
 */
action_id: string, 
/**
 * Human-readable label (e.g. `"Open file"`).
 */
label: string, 
/**
 * Pretty-printed key combo (e.g. `"Ctrl+Shift+D"`).
 */
key_combo: string, 
/**
 * Grouping bucket: `"File"`, `"Edit"`, `"View"`, `"Tools"`, `"App"`.
 */
category: string, };
