// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocStats } from "./DocStats";

export type TabInfo = { id: number, 
/**
 * Document title (from the bookmark file's `<TITLE>` element).
 */
title: string, 
/**
 * Filesystem path the document was opened from, if any.
 */
path: string | null, dirty: boolean, stats: DocStats, };
