// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the "Add treatment" picker.
 */
export type TreatmentInfo = { id: string, name: string, 
/**
 * "url_query_param" | "url_path" | "url_fragment" | "url_host" | "title" |
 * "folder_name" | "cross_field"
 */
category: string, destructive: boolean, };
