// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNode } from "./TreeNode";

/**
 * Recursive folder tree for the left pane.
 */
export type TreeView = { root: TreeNode, };
