// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single tree row used by the v0.0.8 progressive tree expansion API.
 *
 * Unlike [`TreeNode`], this struct does **not** carry its descendants;
 * the UI fetches them lazily through [`crate::commands::get_tree_children`]
 * when the user expands a folder.  The `has_children` flag tells the UI
 * whether to render an expand chevron for this row.
 */
export type TreeNodeLazy = { id: number, name: string, 
/**
 * `true` if this folder has any folder children that the UI should
 * render an expand chevron for; `false` for leaves.  Children
 * themselves are fetched lazily via `get_tree_children`.
 */
has_children: boolean, };
