// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tree-pane row.  Unlike [`TreeNode`] it carries no descendants; the
 * tree pane fetches them with `get_tree_children` on expand.
 */
export type TreeNodeLazy = { id: number, name: string, 
/**
 * Whether the folder contains folders, i.e. gets an expand chevron.
 */
has_children: boolean, };
