// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNode } from "./TreeNode";

/**
 * Full folder tree of a document (merge picker).
 */
export type TreeView = { root: TreeNode, };
